import React from 'react'
import SoftServant from '../../../components/dashboard/softservant/SoftServant';

export const metadata = {
  title: "GranularX Finance - My SoftServant",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <SoftServant />
  )
}

export default page