import React from 'react'
import Messages from '../../../components/dashboard/messages/Messages';

export const metadata = {
  title: "GranularX Finance - My Chats",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <Messages />
  )
}

export default page