import React from 'react'
import Register from "@/components/auth/Register"

export const metadata = {
  title: "GranularX Finance - Create Account",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <Register />
  )
}

export default page