import React from 'react'
import Payment from '../../../components/dashboard/payment/Payment'

export const metadata = {
  title: "GranularX Finance - My Wallet",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <Payment />
  )
}

export default page