import React from 'react'
import Register from "@/components/auth/Register"

export const metadata = {
  title: "GranularX Finance - Create Account",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <main className="min-h-screen bg-white dark:bg-[#141F1F]">
      <div className="container mx-auto">
        <Register />
      </div>
    </main>
  )
}

export default page