import React from 'react'
import Setting from '@/components/dashboard/settings/Setting'

export const metadata = {
  title: "GranularX Finance - Settings",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <Setting />
  )
}

export default page