import type { Metadata } from "next";
// import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import ThemeToggleButton from "@/components/themeToggle/ThemeToggleButton";

// const space = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GranularX Finance",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-white`}>
        <ThemeProvider attribute="class">
          {children}

          <ThemeToggleButton />
        </ThemeProvider>
      </body>
    </html>
  );
}
