import type { Metadata } from "next";
// import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Toaster } from 'react-hot-toast'
import ThemeToggleButton from "@/components/themeToggle/ThemeToggleButton";
import { SessionProvider } from "next-auth/react";

// const space = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GranularX Finance",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-white transition-all ease-in-out duration-200 scroll-smooth`}>
        <ThemeProvider attribute="class" defaultTheme="light">
          <SessionProvider>
            {children}
          </SessionProvider>

          <Toaster />
          {/* <ThemeToggleButton /> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
