import React from 'react'
import Wallet from '../../../components/dashboard/wallet/Wallet'

export const metadata = {
  title: "GranularX Finance - My Wallet",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <Wallet />
  )
}

export default page