import React from 'react'
import MessageContainer from '@/components/MessageContainer';

export const metadata = {
  title: "GranularX Finance - My Chats",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <MessageContainer />
  )
}

export default page