import React from 'react'
import Verify from "@/components/auth/Verify"

export const metadata = {
  title: "GranularX Finance - Verify your account",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <main className="min-h-screen bg-white dark:bg-[#141F1F]">
      <div className="container mx-auto">
        <Verify />
      </div>
    </main>
  )
}

export default page