import React from 'react'
import Verses from '../../../components/dashboard/verses/Verses';

export const metadata = {
  title: "GranularX Finance - My Verses",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <Verses />
  )
}

export default page