import React from 'react'
import Mailbox from '../../../components/dashboard/mailbox/Mailbox';

export const metadata = {
  title: "GranularX Finance - My Mailbox",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <Mailbox />
  )
}

export default page