import React from 'react'
import Signin from "@/components/auth/Signin"

export const metadata = {
  title: "GranularX Finance - Sign In",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <main className="min-h-screen bg-white dark:bg-[#141F1F]">
      <div className="container mx-auto">
        <Signin />
      </div>
    </main>
  )
}

export default page