import React from 'react'
import Reset from "@/components/auth/Reset"

export const metadata = {
  title: "GranularX Finance - Reset Password",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <main className="min-h-screen bg-white dark:bg-[#141F1F]">
      <div className="container mx-auto">
        <Reset />
      </div>
    </main>
  )
}

export default page