import React from 'react'
import Dashboard from "@/components/dashboard/Dashboard"

export const metadata = {
  title: "GranularX Finance - Dashboard",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <Dashboard />
  )
}

export default page